# Generated by Django 3.0.4 on 2022-03-01 22:20

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='orders',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
