# Generated by Django 3.0.4 on 2022-03-02 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_journal_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='pay_type',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='phone',
        ),
    ]
