# Generated by Django 3.0.4 on 2022-03-04 20:17

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_auto_20220302_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='orders',
            field=jsonfield.fields.JSONField(),
        ),
    ]
