# Generated by Django 3.0.4 on 2022-02-27 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_auto_20220226_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='session_id',
            field=models.CharField(max_length=50, verbose_name='Сессия ID'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_app.Cart', verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_app.Status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store_app.Cart', verbose_name='Корзина'),
        ),
    ]
