# Generated by Django 3.0.4 on 2022-04-17 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_auto_20220318_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='total_cost',
            field=models.PositiveIntegerField(default=0, verbose_name='Общая себестоимость продукта'),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Кол-во')),
                ('date_of_purchase', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата продажи')),
                ('purchase_price_per_unit', models.IntegerField(null=True, verbose_name='Цена закупки за единицу')),
                ('sale_price_per_unit', models.IntegerField(verbose_name='Цена продажи за единицу')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_app.Product', verbose_name='Продукт')),
                ('storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_app.Storage', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Кол-во')),
                ('date_of_purchase', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата закупки')),
                ('price_per_unit', models.IntegerField(verbose_name='Цена покупки за единицу')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_app.Product', verbose_name='Продукт')),
                ('storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_app.Storage', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Закупка',
                'verbose_name_plural': 'Закупки',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='storege',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_app.Storage', verbose_name='Склад'),
        ),
    ]
