# Generated by Django 3.0.4 on 2022-05-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0006_auto_20220417_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price_per_unit',
            field=models.PositiveIntegerField(null=True, verbose_name='Цена покупки(за единицу)'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price_per_unit',
            field=models.PositiveIntegerField(null=True, verbose_name='Цена продажи(за единицу)'),
        ),
    ]
