# Generated by Django 3.0.4 on 2022-05-01 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0007_auto_20220501_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='storage',
        ),
    ]
