# Generated by Django 3.0.4 on 2022-05-16 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0011_auto_20220516_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
