# Generated by Django 3.0.4 on 2022-05-16 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0013_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
