# Generated by Django 3.0.4 on 2022-05-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0015_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_of_purchase',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата продажи'),
        ),
    ]
