# Generated by Django 3.0.4 on 2022-03-04 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0003_purchase_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='price_per_unit',
            field=models.IntegerField(verbose_name='Цена покупки за единицу'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage_app.Product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.IntegerField(verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage_app.Storage', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price_per_unit',
            field=models.IntegerField(verbose_name='Цена продажи за единицу'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage_app.Product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.IntegerField(verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage_app.Storage', verbose_name='Склад'),
        ),
    ]
