# Generated by Django 3.0.4 on 2022-03-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0004_auto_20220305_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
        migrations.AddField(
            model_name='product',
            name='total_cost',
            field=models.PositiveIntegerField(default=0, verbose_name='Общая себестоимость продукта'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='product',
            field=models.ManyToManyField(to='storage_app.Product', verbose_name='Продукты'),
        ),
        migrations.DeleteModel(
            name='Manual',
        ),
    ]
