# Generated by Django 3.0.4 on 2022-03-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0005_auto_20220309_0555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='price_per_unit',
            new_name='sale_price_per_unit',
        ),
        migrations.AddField(
            model_name='sale',
            name='purchase_price_per_unit',
            field=models.IntegerField(null=True, verbose_name='Цена закупки за единицу'),
        ),
    ]
