# Generated by Django 3.0.4 on 2022-03-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0006_auto_20220309_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_per_unit',
            field=models.IntegerField(null=True, verbose_name='Цена за единицу'),
        ),
    ]
