# Generated by Django 3.0.4 on 2022-03-17 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0008_auto_20220317_0632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='storege',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage_app.Storage', verbose_name='Склад'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='date_of_purchase',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата закупки'),
        ),
        migrations.AddField(
            model_name='sale',
            name='date_of_purchase',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата продажи'),
        ),
    ]
